# coding: utf-8

"""
    pix_recebimentos

    APis Pix Recebimentos para Clientes (regulatórias).   # noqa: E501

    OpenAPI spec version: 1.40.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pix_recebimento_itau
from pix_recebimento_itau.pix_model.cobrancas_parametros import CobrancasParametros  # noqa: E501
from pix_recebimento_itau.rest import ApiException


class TestCobrancasParametros(unittest.TestCase):
    """CobrancasParametros unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCobrancasParametros(self):
        """Test CobrancasParametros"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pix_recebimento_itau.models.cobrancas_parametros.CobrancasParametros()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
