# coding: utf-8

"""
    pix_recebimentos

    APis Pix Recebimentos para Clientes (regulatórias).   # noqa: E501

    OpenAPI spec version: 1.40.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pix_recebimento_itau
from pix_recebimento.default_api import DefaultApi  # noqa: E501
from pix_recebimento_itau.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = pix_recebimento.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_d_elete_webhookchave(self):
        """Test case for d_elete_webhookchave

        """
        pass

    def test_g_et_cob(self):
        """Test case for g_et_cob

        """
        pass

    def test_g_et_cobtxid(self):
        """Test case for g_et_cobtxid

        """
        pass

    def test_g_et_cobtxidqrcode(self):
        """Test case for g_et_cobtxidqrcode

        """
        pass

    def test_g_et_pix(self):
        """Test case for g_et_pix

        """
        pass

    def test_g_et_pixe2eid(self):
        """Test case for g_et_pixe2eid

        """
        pass

    def test_g_et_pixe2eiddevolucaoid(self):
        """Test case for g_et_pixe2eiddevolucaoid

        """
        pass

    def test_g_et_webhook(self):
        """Test case for g_et_webhook

        """
        pass

    def test_g_et_webhookchave(self):
        """Test case for g_et_webhookchave

        """
        pass

    def test_p_atch_cobtxid(self):
        """Test case for p_atch_cobtxid

        """
        pass

    def test_p_ut_cobtxid(self):
        """Test case for p_ut_cobtxid

        """
        pass

    def test_p_ut_pixe2eiddevolucaoid(self):
        """Test case for p_ut_pixe2eiddevolucaoid

        """
        pass

    def test_p_ut_webhookchave(self):
        """Test case for p_ut_webhookchave

        """
        pass


if __name__ == '__main__':
    unittest.main()
