# coding: utf-8

"""
    pix_recebimentos

    APis Pix Recebimentos para Clientes (regulatórias).   # noqa: E501

    OpenAPI spec version: 1.40.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CobrancaPutRequestCalendario(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'expiracao': 'int'
    }

    attribute_map = {
        'expiracao': 'expiracao'
    }

    def __init__(self, expiracao=None):  # noqa: E501
        """CobrancaPutRequestCalendario - a model defined in Swagger"""  # noqa: E501

        self._expiracao = None
        self.discriminator = None

        if expiracao is not None:
            self.expiracao = expiracao

    @property
    def expiracao(self):
        """Gets the expiracao of this CobrancaPutRequestCalendario.  # noqa: E501

        Tempo de vida da cobrança, especificado em segundos  # noqa: E501

        :return: The expiracao of this CobrancaPutRequestCalendario.  # noqa: E501
        :rtype: int
        """
        return self._expiracao

    @expiracao.setter
    def expiracao(self, expiracao):
        """Sets the expiracao of this CobrancaPutRequestCalendario.

        Tempo de vida da cobrança, especificado em segundos  # noqa: E501

        :param expiracao: The expiracao of this CobrancaPutRequestCalendario.  # noqa: E501
        :type: int
        """

        self._expiracao = expiracao

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CobrancaPutRequestCalendario, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CobrancaPutRequestCalendario):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
