# coding: utf-8

"""
    pix_recebimentos

    APis Pix Recebimentos para Clientes (regulatórias).   # noqa: E501

    OpenAPI spec version: 1.40.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DevolucaoPutResponseHorario(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'solicitacao': 'datetime',
        'liquidacao': 'datetime'
    }

    attribute_map = {
        'solicitacao': 'solicitacao',
        'liquidacao': 'liquidacao'
    }

    def __init__(self, solicitacao=None, liquidacao=None):  # noqa: E501
        """DevolucaoPutResponseHorario - a model defined in Swagger"""  # noqa: E501

        self._solicitacao = None
        self._liquidacao = None
        self.discriminator = None

        self.solicitacao = solicitacao
        if liquidacao is not None:
            self.liquidacao = liquidacao

    @property
    def solicitacao(self):
        """Gets the solicitacao of this DevolucaoPutResponseHorario.  # noqa: E501

        Horário no qual a devolução foi solicitada no PSP.  # noqa: E501

        :return: The solicitacao of this DevolucaoPutResponseHorario.  # noqa: E501
        :rtype: datetime
        """
        return self._solicitacao

    @solicitacao.setter
    def solicitacao(self, solicitacao):
        """Sets the solicitacao of this DevolucaoPutResponseHorario.

        Horário no qual a devolução foi solicitada no PSP.  # noqa: E501

        :param solicitacao: The solicitacao of this DevolucaoPutResponseHorario.  # noqa: E501
        :type: datetime
        """
        if solicitacao is None:
            raise ValueError("Invalid value for `solicitacao`, must not be `None`")  # noqa: E501

        self._solicitacao = solicitacao

    @property
    def liquidacao(self):
        """Gets the liquidacao of this DevolucaoPutResponseHorario.  # noqa: E501

        Horário no qual a devolução foi liquidada no PSP.  # noqa: E501

        :return: The liquidacao of this DevolucaoPutResponseHorario.  # noqa: E501
        :rtype: datetime
        """
        return self._liquidacao

    @liquidacao.setter
    def liquidacao(self, liquidacao):
        """Sets the liquidacao of this DevolucaoPutResponseHorario.

        Horário no qual a devolução foi liquidada no PSP.  # noqa: E501

        :param liquidacao: The liquidacao of this DevolucaoPutResponseHorario.  # noqa: E501
        :type: datetime
        """

        self._liquidacao = liquidacao

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DevolucaoPutResponseHorario, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DevolucaoPutResponseHorario):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
