# coding: utf-8

"""
    pix_recebimentos

    APis Pix Recebimentos para Clientes (regulatórias).   # noqa: E501

    OpenAPI spec version: 1.40.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Pixs(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'parametros': 'PixsParametros',
        'pix': 'list[PixsPix]'
    }

    attribute_map = {
        'parametros': 'parametros',
        'pix': 'pix'
    }

    def __init__(self, parametros=None, pix=None):  # noqa: E501
        """Pixs - a model defined in Swagger"""  # noqa: E501

        self._parametros = None
        self._pix = None
        self.discriminator = None

        self.parametros = parametros
        if pix is not None:
            self.pix = pix

    @property
    def parametros(self):
        """Gets the parametros of this Pixs.  # noqa: E501


        :return: The parametros of this Pixs.  # noqa: E501
        :rtype: PixsParametros
        """
        return self._parametros

    @parametros.setter
    def parametros(self, parametros):
        """Sets the parametros of this Pixs.


        :param parametros: The parametros of this Pixs.  # noqa: E501
        :type: PixsParametros
        """
        if parametros is None:
            raise ValueError("Invalid value for `parametros`, must not be `None`")  # noqa: E501

        self._parametros = parametros

    @property
    def pix(self):
        """Gets the pix of this Pixs.  # noqa: E501

        Devolucoes registradas no documento  # noqa: E501

        :return: The pix of this Pixs.  # noqa: E501
        :rtype: list[PixsPix]
        """
        return self._pix

    @pix.setter
    def pix(self, pix):
        """Sets the pix of this Pixs.

        Devolucoes registradas no documento  # noqa: E501

        :param pix: The pix of this Pixs.  # noqa: E501
        :type: list[PixsPix]
        """

        self._pix = pix

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Pixs, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Pixs):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
